GET http://localhost:3000/me

###
GET http://localhost:3000/heroes

###
GET http://localhost:3000/heroes/60e55cd3dfeaf4010cce9bb7

###
GET http://localhost:3000/heroes/bio/60e55cd3dfeaf4010cce9bb7

###
POST http://localhost:3000/heroes
Content-Type: application/json

{
      "id": "69",
      "name": "Batman",
      "powerstats": {
        "intelligence": "81",
        "strength": "40",
        "speed": "29",
        "durability": "55",
        "power": "63",
        "combat": "90"
      },
      "biography": {
        "full-name": "Terry McGinnis",
        "alter-egos": "No alter egos found.",
        "aliases": "The Tomorrow Knight",
        "place-of-birth": "Gotham City, 25th Century",
        "first-appearance": "Batman Beyond #1",
        "publisher": "DC Comics",
        "alignment": "good"
      }
}

###
DELETE  http://localhost:3000/heroes/60e55cd3dfeaf4010cce9bb7